Part 1: Calculate the Mean, Median, and Standard deviation

In [95]:
 from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [96]:
import pandas as pd

In [97]:
import numpy as np

 1. Load the wine dataset from the given ‘wine.csv’ file into a variable

In [98]:
Zain = pd.read_csv("/content/gdrive/MyDrive/wine.csv") #loading data into a varible Zain

In [99]:
Zain.shape

(178, 14)

In [100]:
Zain

Wine  Alcohol  Malic.acid   Ash  ...  Color.int   Hue    OD  Proline
0       1    14.23        1.71  2.43  ...       5.64  1.04  3.92     1065
1       1    13.20        1.78  2.14  ...       4.38  1.05  3.40     1050
2       1    13.16        2.36  2.67  ...       5.68  1.03  3.17     1185
3       1    14.37        1.95  2.50  ...       7.80  0.86  3.45     1480
4       1    13.24        2.59  2.87  ...       4.32  1.04  2.93      735
..    ...      ...         ...   ...  ...        ...   ...   ...      ...
173     3    13.71        5.65  2.45  ...       7.70  0.64  1.74      740
174     3    13.40        3.91  2.48  ...       7.30  0.70  1.56      750
175     3    13.27        4.28  2.26  ...      10.20  0.59  1.56      835
176     3    13.17        2.59  2.37  ...       9.30  0.60  1.62      840
177     3    14.13        4.10  2.74  ...       9.20  0.61  1.60      560

[178 rows x 14 columns]

In [101]:
#2. From the variable, extract the numerical information into a new variable, say scores.
score = Zain.drop('Wine', axis=1)
score

Alcohol  Malic.acid   Ash   Acl  ...  Color.int   Hue    OD  Proline
0      14.23        1.71  2.43  15.6  ...       5.64  1.04  3.92     1065
1      13.20        1.78  2.14  11.2  ...       4.38  1.05  3.40     1050
2      13.16        2.36  2.67  18.6  ...       5.68  1.03  3.17     1185
3      14.37        1.95  2.50  16.8  ...       7.80  0.86  3.45     1480
4      13.24        2.59  2.87  21.0  ...       4.32  1.04  2.93      735
..       ...         ...   ...   ...  ...        ...   ...   ...      ...
173    13.71        5.65  2.45  20.5  ...       7.70  0.64  1.74      740
174    13.40        3.91  2.48  23.0  ...       7.30  0.70  1.56      750
175    13.27        4.28  2.26  20.0  ...      10.20  0.59  1.56      835
176    13.17        2.59  2.37  20.0  ...       9.30  0.60  1.62      840
177    14.13        4.10  2.74  24.5  ...       9.20  0.61  1.60      560

[178 rows x 13 columns]

In [102]:
#3. Calculate the row-wise,column-wise, and overall mean, median, and standard deviation of the dataset.
#In this question write separate functions for each operation and pass the variable (scores) as the parameter to the function.

np.mean(score)   #column wise mean

Alcohol                  13.000618
Malic.acid                2.336348
Ash                       2.366517
Acl                      19.494944
Mg                       99.741573
Phenols                   2.295112
Flavanoids                2.029270
Nonflavanoid.phenols      0.361854
Proanth                   1.590899
Color.int                 5.058090
Hue                       0.957449
OD                        2.611685
Proline                 746.893258
dtype: float64

In [103]:
np.mean(score, axis = 1)  #mean row-wise


0       95.769231
1       91.853846
2      103.216923
3      126.960769
4       69.899231
          ...    
173     68.558462
174     69.903077
175     77.786154
176     77.997692
177     55.200000
Length: 178, dtype: float64

In [104]:
x=score.mean(axis= 0)          #over all mean 
y=score.mean(axis= 1)
np.mean(x)

69.13366292091617

In [105]:
np.median(score)  #over all median

2.685

In [106]:
np.median(score, axis = 0)  #median column wise

array([1.305e+01, 1.865e+00, 2.360e+00, 1.950e+01, 9.800e+01, 2.355e+00,
       2.135e+00, 3.400e-01, 1.555e+00, 4.690e+00, 9.650e-01, 2.780e+00,
       6.735e+02])

In [107]:
np.median(score,axis =1)   #median row-wise

array([3.06, 2.76, 3.17, 3.49, 2.87, 3.27, 2.52, 2.61, 2.85, 3.15, 3.17,
       2.43, 2.76, 3.1 , 3.3 , 2.88, 2.8 , 2.95, 3.3 , 3.1 , 3.17, 3.52,
       2.88, 2.52, 2.61, 3.2 , 2.94, 2.4 , 2.97, 2.65, 3.  , 2.88, 2.69,
       2.95, 2.65, 2.98, 2.78, 2.51, 2.64, 3.53, 3.29, 3.  , 3.56, 3.  ,
       3.  , 3.33, 3.44, 3.33, 2.75, 3.1 , 2.91, 2.99, 3.74, 2.93, 2.9 ,
       2.96, 3.2 , 3.  , 3.4 , 1.82, 2.05, 2.02, 2.1 , 3.1 , 2.23, 2.56,
       3.18, 2.11, 2.36, 2.5 , 1.82, 2.95, 2.24, 3.3 , 3.13, 1.92, 2.03,
       2.52, 2.31, 2.83, 2.42, 2.53, 2.2 , 2.32, 2.58, 2.24, 2.26, 2.6 ,
       2.46, 2.2 , 2.27, 2.42, 2.06, 2.45, 2.96, 2.6 , 2.26, 2.55, 3.52,
       2.85, 2.23, 1.9 , 2.56, 2.06, 2.2 , 2.55, 2.12, 2.28, 2.36, 2.74,
       3.18, 2.43, 2.68, 2.48, 2.56, 2.2 , 1.98, 2.09, 2.12, 2.  , 2.9 ,
       3.69, 2.73, 2.65, 3.03, 2.65, 2.84, 2.44, 2.3 , 2.57, 1.51, 2.4 ,
       2.31, 2.36, 2.  , 2.2 , 2.54, 2.64, 2.19, 2.61, 2.7 , 2.47, 2.72,
       2.35, 2.2 , 2.15, 2.23, 2.48, 2.38, 2.36, 2.

In [108]:
p=score.std(axis= 0)         #over all standard deviation 
q=score.std(axis= 1)
np.std(p)

83.4279566113766

In [109]:
np.std(score, axis = 1)   #row-wise standard deviation

0      281.704533
1      277.789758
2      313.360079
3      391.665635
4      194.404491
          ...    
173    195.376371
174    198.101075
175    220.781381
176    222.156135
177    147.836498
Length: 178, dtype: float64

In [110]:
np.std(score,axis = 0)  #column -wise standard deviation

Alcohol                   0.809543
Malic.acid                1.114004
Ash                       0.273572
Acl                       3.330170
Mg                       14.242308
Phenols                   0.624091
Flavanoids                0.996049
Nonflavanoid.phenols      0.124103
Proanth                   0.570749
Color.int                 2.311765
Hue                       0.227929
OD                        0.707993
Proline                 314.021657
dtype: float64

#Part 2: Calculate the pearson correlation and covariance matrix

In [111]:
#1. Take the ‘Alcohol’ and ‘Proline’ as the features from the ‘wine.csv’ dataset 

X=score.loc[0:178,['Alcohol', 'Proline']]
X

Alcohol  Proline
0      14.23     1065
1      13.20     1050
2      13.16     1185
3      14.37     1480
4      13.24      735
..       ...      ...
173    13.71      740
174    13.40      750
175    13.27      835
176    13.17      840
177    14.13      560

[178 rows x 2 columns]

In [112]:
#calculate the Pearson’s correlation for the same.

X.corr()  #corr is in pandas lib  

Alcohol  Proline
Alcohol  1.00000  0.64372
Proline  0.64372  1.00000

In [113]:
#2. Take any 5 features from the ‘wine.csv’ dataset and load them in a matrix. Thereafter, create the covariance matrix of the same

Y=score.loc[0:178,['Alcohol', 'Proline','Mg','Phenols', 'Hue']]
Y

Alcohol  Proline   Mg  Phenols   Hue
0      14.23     1065  127     2.80  1.04
1      13.20     1050  100     2.65  1.05
2      13.16     1185  101     2.80  1.03
3      14.37     1480  113     3.85  0.86
4      13.24      735  118     2.80  1.04
..       ...      ...  ...      ...   ...
173    13.71      740   95     1.68  0.64
174    13.40      750  102     1.80  0.70
175    13.27      835  120     1.59  0.59
176    13.17      840  120     1.65  0.60
177    14.13      560   96     2.05  0.61

[178 rows x 5 columns]

In [114]:
a=np.cov(Y)
a

array([[214427.88338 , 212185.05285 , 239926.589035, ..., 167461.60285 ,
        168491.839305, 111493.71131 ],
       [212185.05285 , 210087.81075 , 237610.101825, ..., 165611.594   ,
        166633.831725, 110194.2147  ],
       [239926.589035, 237610.101825, 268762.87462 , ..., 187219.34095 ,
        188376.51351 , 124540.14767 ],
       ...,
       [167461.60285 , 165611.594   , 187219.34095 , ..., 130862.33215 ,
        131664.6189  ,  87182.32835 ],
       [168491.839305, 166633.831725, 188376.51351 , ..., 131664.6189  ,
        132471.92403 ,  87714.81906 ],
       [111493.71131 , 110194.2147  , 124540.14767 , ...,  87182.32835 ,
         87714.81906 ,  58122.73867 ]])